version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - vscode:/vscode:cached
    ports:
      - "22:22"
    command: sleep infinity
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  vscode:
